version: '2.1'

services:
  orchestrator:
    build: ./orchestrator
    image: orchestrator:latest
    command: python3 -u db.py
    container_name: orchestrator
    ports:
      - "80:80"
    volumes:
      - ./orchestrator:/orchestrator
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    build: ./rabbitmq
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    networks:
      - backend

  slave:
    build: ./worker
    image: slave:latest
    command: python3 -u worker.py
    container_name: slave
    volumes:
    - ./worker:/worker
    links:
      - mongoslave
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - WORKER_TYPE=slave
      - DB_HOSTNAME=mongoslave

  mongoslave:
    image: mongo:latest
    container_name: mongoslave

  master:
    build: ./worker
    image: master:latest
    command: python3 -u worker.py
    container_name: master
    volumes:
      - ./worker:/worker
    links:
      - mongomaster
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - WORKER_TYPE=master
      - DB_HOSTNAME=mongomaster

  mongomaster:
    image: mongo:latest
    container_name: mongomaster

networks:
  backend: