version: '2.1'

services:
  orchestrator:
    build: ./orchestrator
    image: orchestrator:latest
    command: python3 -u db.py
    container_name: orchestrator
    ports:
      - "80:80"
    volumes:
      - ./orchestrator:/orchestrator
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    build: ./rabbitmq
    networks:
      - backend
    container_name: rabbitmq
    hostname: rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - backend
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888;2181
    ports:
    - 2181:2181

  slave1:
    build: ./worker
    image: slave:latest
    command: python3 -u worker.py
    container_name: slave1
    volumes:
    - ./worker:/worker
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - WORKER_TYPE=slave
      - DB_HOSTNAME=mongoslave1
      - NODE_NAME=slave1
    entrypoint: ["sh", "cleanup.sh"]

  mongoslave1:
    image: mongo:latest
    container_name: mongoslave1
    networks:
      - backend

  master:
    build: ./worker
    image: master:latest
    command: python3 -u worker.py
    container_name: master
    volumes:
      - ./worker:/worker
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - WORKER_TYPE=master
      - DB_HOSTNAME=mongomaster
      - NODE_NAME=master
    entrypoint: ["sh", "cleanup.sh"]

  mongomaster:
    image: mongo:latest
    container_name: mongomaster
    networks:
      - backend

networks:
  backend: